version: '3.9'

services:
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build: .
    restart: always
    command: >
      sh -c "python manage.py migrate &&
      python manage.py load_uszips &&
      python manage.py load_cars &&
      python manage.py create_superuser &&
      cron &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  postgres_data: